version: '2.3'

services:
  python:
    build:
        context: ./
        dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    image: object_detection_api:tf2
    container_name: object_detection_api
    ports:
      - 8882:8888
    volumes:
      - ./:/home/tensorflow/workspace/
    command: /bin/bash -c "jupyter lab --port 8888 --ip=0.0.0.0"
    # command: /bin/bash -c "while :; do sleep 10; done"
